# SPDX-FileCopyrightText: 2021-2022 Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[toolchain]
channel = "nightly-2021-10-16"
components = [ "rust-src", "rustfmt" ]
targets = [ "thumbv7em-none-eabihf" ]
